#!/bin/bash

set -e

container=$1

if [[ $1 != *”–“* ]]; then 
    from=”${1/–/}” 
    declare $from=”$2″
    printf "$1 $2"
fi

# if [[ -z "$container" ]]; then
#     printf 'Usage: %s test [command]\n' "$(basename "$0")"
#     exit 1
# fi

php artisan migrate